import React from 'react';
import { Memory } from '../types';
import { motion } from 'framer-motion';
import { MemoryCard } from './MemoryCard';

interface TimelineProps { memories: Memory[]; onMemoryClick: (memory: Memory) => void; user: any; activeTab: 'personal' | 'team'; setActiveTab: (tab: 'personal' | 'team') => void; shelves: any[]; handleShelfClick: (shelf: string) => void; }

export function Timeline({ memories, onMemoryClick, user, activeTab, setActiveTab, shelves, handleShelfClick }: TimelineProps) {
  return (
    <div className="space-y-32">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-16 border-b border-border/10 pb-16">
        <div className="space-y-16 flex-1">
          <div className="flex items-center gap-16">
            <div className="flex items-center gap-4 group cursor-default"><div className="w-14 h-14 bg-accent rounded-full flex items-center justify-center shadow-[0_0_40px_rgba(245,166,35,0.15)] group-hover:scale-110 transition-transform duration-700"><span className="font-mono text-xl font-bold text-background">R</span></div><div className="flex flex-col"><span className="font-mono text-[9px] uppercase tracking-[0.4em] text-accent">Recall System</span><span className="font-mono text-[7px] uppercase tracking-[0.2em] text-muted-foreground/40">v1.0.4 — ARCHIVAL</span></div></div>
            <div className="flex bg-card/40 backdrop-blur-xl border border-border/50 p-1.5 rounded-full"><button onClick={() => setActiveTab('personal')} className={`px-8 py-2.5 rounded-full font-mono text-[9px] uppercase tracking-widest transition-all duration-500 ${activeTab === 'personal' ? 'bg-accent text-background shadow-lg' : 'text-muted-foreground hover:text-foreground'}`}>Personal</button><button onClick={() => setActiveTab('team')} className={`px-8 py-2.5 rounded-full font-mono text-[9px] uppercase tracking-widest transition-all duration-500 flex items-center gap-2 ${activeTab === 'team' ? 'bg-accent text-background shadow-lg' : 'text-muted-foreground hover:text-foreground'}`}>Shared Vault</button></div>
          </div>
          <h1 className="text-7xl md:text-9xl font-serif leading-[0.9] tracking-tighter max-w-4xl">Welcome back, <br/><span className="italic text-accent/90">{user.name.split(' ')[0]}.</span></h1>
        </div>
        <div className="flex gap-16 pr-4"><div className="space-y-3"><span className="font-mono text-[9px] uppercase tracking-[0.3em] text-muted-foreground/40 block">Memory Score</span><div className="flex items-baseline gap-3"><span className="text-5xl font-serif tracking-tight">{memories.length.toLocaleString()}</span><span className="font-mono text-[10px] text-muted-foreground/30 uppercase tracking-widest">fragments</span></div></div><div className="space-y-3"><span className="font-mono text-[9px] uppercase tracking-[0.3em] text-muted-foreground/40 block">Archival Streak</span><div className="flex items-baseline gap-3"><span className="text-5xl font-serif text-accent tracking-tight">14</span><span className="font-mono text-[9px] uppercase tracking-[0.3em] text-accent/40">Cycles</span></div></div></div>
      </header>
      {activeTab === 'personal' ? (
        <>
          <section className="p-12 md:p-16 border border-border/40 bg-card/20 backdrop-blur-md rounded-[48px] relative overflow-hidden group"><div className="absolute top-0 right-0 p-12"><div className="w-10 h-10 rounded-full border border-accent/20 flex items-center justify-center font-mono text-[11px] text-accent opacity-30 group-hover:opacity-100 group-hover:scale-110 transition-all duration-1000">P1</div></div><div className="max-w-4xl space-y-8"><div className="flex items-center gap-4"><div className="h-px w-8 bg-accent/40" /><span className="font-mono text-[9px] uppercase tracking-[0.4em] text-accent">Neural Profile — Current Arc</span></div><p className="text-3xl md:text-4xl font-serif leading-[1.3] italic text-foreground/90">"Your recent saves indicate a deep immersion in <span className="text-accent underline decoration-accent/20 underline-offset-8">brutalist architecture</span> and systems design. This trajectory suggests an upcoming shift toward high-craft digital archeology."</p></div></section>
          <section className="space-y-12"><div className="flex items-center justify-between px-2"><div className="flex items-center gap-4"><h3 className="text-4xl font-serif tracking-tight">Daily Spark</h3><span className="px-3 py-1 bg-accent/5 border border-accent/10 rounded-full font-mono text-[7px] uppercase tracking-[0.3em] text-accent">Resurfacing</span></div><div className="h-px flex-1 bg-border/20 mx-12" /></div><div onClick={() => onMemoryClick(memories[0])} className="group relative overflow-hidden rounded-[48px] border border-border/40 bg-card/40 hover:border-accent/40 transition-all duration-1000 cursor-pointer shadow-2xl"><div className="p-12 md:p-20"><span className="font-mono text-[9px] uppercase tracking-[0.4em] text-muted-foreground/40 mb-10 block">Archived 8 months ago — Architecture Vault</span><h2 className="text-5xl md:text-7xl font-serif mb-16 max-w-5xl leading-[1.1] tracking-tight group-hover:text-accent transition-colors duration-1000 italic">"{memories[0]?.content || 'The best way to predict the future is to create it.'}"</h2><div className="flex items-center gap-8"><div className="px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 font-mono text-[9px] text-blue-400 uppercase tracking-widest">X</div><div className="flex items-center gap-3"><div className="w-1.5 h-1.5 bg-accent/40 rounded-full animate-pulse" /><span className="font-mono text-[10px] text-muted-foreground/60 uppercase tracking-[0.2em]">High Resonance detected</span></div></div></div></div></section>
          <section className="space-y-16"><div className="flex items-center justify-between px-2"><h3 className="text-4xl font-serif tracking-tight">Active Shelves</h3><button className="font-mono text-[9px] uppercase tracking-[0.3em] text-accent hover:text-accent/60 transition-colors flex items-center gap-3 group"><span className="text-lg group-hover:rotate-90 transition-transform duration-500">+</span>Initialize New Shelf</button></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 md:gap-14">{shelves.map((shelf, i) => (<motion.div key={shelf.name} whileHover={{ y: -12 }} onClick={() => handleShelfClick(shelf.name)} className={`group relative aspect-[4/5] rounded-[48px] border border-border/40 bg-card/40 p-12 hover:border-accent/40 transition-all duration-1000 cursor-pointer overflow-hidden shadow-xl ${shelf.special ? 'bg-zinc-900/30' : ''}`}><div className="relative z-10 h-full flex flex-col justify-between"><div className="space-y-6"><div className={`font-mono text-4xl font-bold ${shelf.color} opacity-20 group-hover:opacity-100 group-hover:scale-110 transition-all duration-1000 origin-left`}>{shelf.label}</div><h4 className="text-4xl md:text-5xl font-serif group-hover:translate-x-3 transition-transform duration-1000 tracking-tighter">{shelf.name}</h4></div><div className="space-y-4"><div className="h-[2px] w-12 bg-accent/40 group-hover:w-full transition-all duration-1000" /><div className="flex items-center justify-between font-mono text-[9px] uppercase tracking-[0.3em] text-muted-foreground/40"><span>{shelf.count} Fragments</span><span className="opacity-0 group-hover:opacity-100 translate-x-4 group-hover:translate-x-0 transition-all duration-1000 text-accent">Access Vault →</span></div></div></div></motion.div>))}</div></section>
        </>
      ) : (
        <section className="py-60 text-center space-y-16 max-w-4xl mx-auto"><div className="w-28 h-28 bg-card/40 border border-accent/20 rounded-full flex items-center justify-center mx-auto shadow-2xl font-mono text-4xl text-accent animate-pulse">T</div><div className="space-y-6"><h3 className="text-6xl md:text-7xl font-serif tracking-tighter leading-tight">Shared Creative <br/>Consciousness</h3><p className="text-muted-foreground/60 font-mono text-xs leading-loose uppercase tracking-[0.3em]">Synchronize vaults with your inner circle. <br/>Build a collective library of inspiration.</p></div><button className="px-16 py-8 bg-accent text-background rounded-full font-mono text-[10px] uppercase tracking-[0.4em] hover:scale-105 active:scale-95 transition-all duration-500 shadow-[0_30px_60px_rgba(245,166,35,0.2)]">Initialize Shared Vault</button></section>
      )}
    </div>
  );
}
